// GameScene.swift
// Renders the deterministic sim. SpriteKit ONLY draws state the sim produces;
// it never moves anything itself (no SKPhysics, no SKAction movement). A
// SceneDriver advances the game one fixed 60 Hz tick at a time; rendering
// interpolates between the previous and current state for smoothness.
//
// Coordinate mapping: the sim is y-down with origin at the top-left; the scene
// is y-up with origin at the bottom-left. So skY = worldHeight - simY. The only
// float usage is this render-time conversion, which is allowed.

import SpriteKit
import ArrowClashSim

final class GameScene: SKScene {
    private let config = GameConfig.default
    private let map: TileMap
    private let tileColor: SKColor
    private let input: InputBus
    private let driver: SceneDriver

    private let tickDuration: TimeInterval = 1.0 / 60.0
    private var accumulator: TimeInterval = 0
    private var lastTime: TimeInterval = 0

    private let world = SKNode() // everything that can shake
    private var playerNodes: [AnimatedAvatarNode] = []
    private var arrowNodes: [SKSpriteNode] = []
    private let spriteProvider: SpriteProvider = ChibiSpriteProvider.shared
    private let mapId: Int
    private static let runThreshold: Int32 = 20000 // ~0.3 px/tick in Q16.16
    private var hud = SKLabelNode()
    private var scoreLabel = SKLabelNode()
    private var centerLabel = SKLabelNode()
    private var connectionLabel = SKLabelNode()
    private var flash = SKSpriteNode()
    private var lastCenterText = ""

    // Dark ink color for HUD text so it reads on the pastel backgrounds.
    private static let inkColor = SKColor(red: 0.16, green: 0.14, blue: 0.23, alpha: 1)

    // Fired once when the match ends: (localWon, localKills, totalRounds).
    var onMatchEnd: ((Bool, Int, Int) -> Void)?
    private var matchEndFired = false

    // Per-player avatar (layered look) and resolved colors.
    private let avatars: [Avatar]
    private var trailColors: [SKColor]
    private var trailSpawnTick = 0

    private var worldWidthPx: Float { Float(map.cols * config.tileSize) }
    private var worldHeightPx: Float { Float(map.rows * config.tileSize) }

    init(input: InputBus,
         driver: SceneDriver,
         map: MapDefinition = Maps.default,
         avatars: [Avatar] = [.default, .default],
         tileColor: SKColor = SKColor(red: 0.22, green: 0.24, blue: 0.30, alpha: 1.0),
         bgColor: SKColor = SKColor(red: 0.08, green: 0.09, blue: 0.12, alpha: 1.0)) {
        self.input = input
        self.driver = driver
        self.map = map.tileMap()
        self.mapId = map.id
        self.tileColor = tileColor
        self.avatars = avatars
        self.trailColors = avatars.map { Catalog.color($0.trail) }
        let worldSize = CGSize(
            width: GameConfig.default.tileSize * map.cols,
            height: GameConfig.default.tileSize * map.rows
        )
        super.init(size: worldSize)
        self.scaleMode = .aspectFit
        self.anchorPoint = .zero
        self.backgroundColor = bgColor
    }

    required init?(coder: NSCoder) { fatalError("not used") }

    override func didMove(to view: SKView) {
        // Flat pastel background (the reference style is clean and flat, so no
        // gradient/vignette layers here - backgroundColor does the whole job).
        addChild(world)
        buildTiles()
        buildEntities()
        buildHUD()
        buildFlash()
        AudioManager.shared.preload()
    }

    // MARK: - Build

    // Loads the 16 edge-mask variants for this map's tileset (generated by
    // tools/generate_pixel_art.py). Returns nil if the set is missing, in which
    // case tiles fall back to flat colored squares.
    private func loadTileset() -> [SKTexture]? {
        var textures: [SKTexture] = []
        for mask in 0..<16 {
            guard let url = Bundle.main.url(forResource: "t\(mask)", withExtension: "png",
                                            subdirectory: "Sprites/tiles/theme\(mapId)"),
                  let image = UIImage(contentsOfFile: url.path) else { return nil }
            let tex = SKTexture(image: image)
            tex.filteringMode = .nearest
            textures.append(tex)
        }
        return textures
    }

    private func buildTiles() {
        let ts = CGFloat(config.tileSize)
        let tileset = loadTileset()
        for row in 0..<map.rows {
            for col in 0..<map.cols where map.isSolid(col: col, row: row) {
                let tile: SKSpriteNode
                if let tileset = tileset {
                    // 4-bit solid-neighbor mask (1=N, 2=E, 4=S, 8=W). Neighbors
                    // wrap like the arena does, so edge tiles connect across.
                    var mask = 0
                    if map.isSolid(col: col, row: (row - 1 + map.rows) % map.rows) { mask |= 1 }
                    if map.isSolid(col: (col + 1) % map.cols, row: row) { mask |= 2 }
                    if map.isSolid(col: col, row: (row + 1) % map.rows) { mask |= 4 }
                    if map.isSolid(col: (col - 1 + map.cols) % map.cols, row: row) { mask |= 8 }
                    tile = SKSpriteNode(texture: tileset[mask], size: CGSize(width: ts, height: ts))
                } else {
                    tile = SKSpriteNode(color: tileColor, size: CGSize(width: ts, height: ts))
                }
                let simCx = Float(col * config.tileSize) + Float(config.tileSize) / 2
                let simCy = Float(row * config.tileSize) + Float(config.tileSize) / 2
                tile.position = CGPoint(x: CGFloat(simCx), y: CGFloat(worldHeightPx - simCy))
                world.addChild(tile)
            }
        }
    }

    private func buildEntities() {
        let state = driver.renderStates().current
        let w = CGFloat(config.playerWidth.toFloat)
        let h = CGFloat(config.playerHeight.toFloat)
        for i in 0..<state.players.count {
            let avatar = i < avatars.count ? avatars[i] : .default
            let node = AnimatedAvatarNode(avatar: avatar, provider: spriteProvider,
                                          width: w, height: h, isLocal: i == driver.localPlayer)
            world.addChild(node)
            playerNodes.append(node)
        }
        // Pixel arrow sprite (points right at zero rotation; render rotates it).
        var arrowTexture: SKTexture?
        if let url = Bundle.main.url(forResource: "arrow", withExtension: "png", subdirectory: "Sprites/fx"),
           let image = UIImage(contentsOfFile: url.path) {
            let tex = SKTexture(image: image)
            tex.filteringMode = .nearest
            arrowTexture = tex
        }
        for _ in 0..<state.arrows.count {
            let node: SKSpriteNode
            if let tex = arrowTexture {
                node = SKSpriteNode(texture: tex, size: CGSize(width: 14, height: 5))
            } else {
                node = SKSpriteNode(color: .white, size: CGSize(width: 8, height: 2))
            }
            node.isHidden = true
            world.addChild(node)
            arrowNodes.append(node)
        }
    }

    private func buildHUD() {
        hud.fontName = "Menlo-Bold"
        hud.fontSize = 10
        hud.fontColor = Self.inkColor
        hud.horizontalAlignmentMode = .left
        hud.verticalAlignmentMode = .top
        hud.position = CGPoint(x: 6, y: CGFloat(worldHeightPx) - 4)
        hud.zPosition = 60
        addChild(hud)

        scoreLabel.fontName = "Menlo-Bold"
        scoreLabel.fontSize = 14
        scoreLabel.fontColor = Self.inkColor
        scoreLabel.horizontalAlignmentMode = .center
        scoreLabel.verticalAlignmentMode = .top
        scoreLabel.position = CGPoint(x: CGFloat(worldWidthPx) / 2, y: CGFloat(worldHeightPx) - 4)
        scoreLabel.zPosition = 60
        addChild(scoreLabel)

        centerLabel.fontName = "Menlo-Bold"
        centerLabel.fontSize = 22
        centerLabel.fontColor = Self.inkColor
        centerLabel.horizontalAlignmentMode = .center
        centerLabel.verticalAlignmentMode = .center
        centerLabel.position = CGPoint(x: CGFloat(worldWidthPx) / 2, y: CGFloat(worldHeightPx) * 0.62)
        centerLabel.zPosition = 60
        addChild(centerLabel)

        connectionLabel.fontName = "Menlo-Bold"
        connectionLabel.fontSize = 12
        connectionLabel.fontColor = Self.inkColor
        connectionLabel.horizontalAlignmentMode = .center
        connectionLabel.verticalAlignmentMode = .center
        connectionLabel.position = CGPoint(x: CGFloat(worldWidthPx) / 2, y: CGFloat(worldHeightPx) * 0.42)
        connectionLabel.zPosition = 60
        connectionLabel.isHidden = true
        addChild(connectionLabel)
    }

    private func buildFlash() {
        flash = SKSpriteNode(color: .white, size: CGSize(width: CGFloat(worldWidthPx), height: CGFloat(worldHeightPx)))
        flash.anchorPoint = .zero
        flash.position = .zero
        flash.alpha = 0
        flash.zPosition = 1000
        addChild(flash)
    }

    // MARK: - Loop

    override func update(_ currentTime: TimeInterval) {
        if lastTime == 0 { lastTime = currentTime }
        var frameDelta = currentTime - lastTime
        lastTime = currentTime
        if frameDelta > 0.25 { frameDelta = 0.25 }

        accumulator += frameDelta
        var didTick = false
        while accumulator >= tickDuration {
            driver.advance(localInput: input.consumeForTick())
            accumulator -= tickDuration
            didTick = true
        }

        if didTick {
            let states = driver.renderStates()
            detectEvents(previous: states.previous, current: states.current)
        }

        updateConnectionBanner()
        renderInterpolated(alpha: Float(accumulator / tickDuration), dt: frameDelta)
    }

    // Surfaces link health during an online match: a banner while the peer is
    // quiet (the session stalls rather than predicting forever), and a one-time
    // forfeit win if the peer stays gone past the disconnect timeout.
    private func updateConnectionBanner() {
        switch driver.linkStatus {
        case .healthy:
            connectionLabel.isHidden = true
        case .waiting:
            connectionLabel.isHidden = false
            connectionLabel.fontColor = Self.inkColor
            connectionLabel.text = "RECONNECTING..."
        case .disconnected:
            connectionLabel.isHidden = false
            connectionLabel.fontColor = SKColor(red: 0.55, green: 0.12, blue: 0.12, alpha: 1)
            connectionLabel.text = "OPPONENT DISCONNECTED"
            if !matchEndFired {
                matchEndFired = true
                let state = driver.renderStates().current
                let me = driver.localPlayer
                let kills = me < state.scores.count ? state.scores[me] : 0
                let rounds = state.scores.reduce(0, +)
                onMatchEnd?(true, kills, rounds)
            }
        }
    }

    // MARK: - Juice (render-only)

    // Compares the last tick's before/after states to fire sounds and effects.
    // Movement sounds are local-player only (those inputs aren't predicted, so
    // they don't flicker under rollback); death effects fire for either player.
    private func detectEvents(previous: GameState, current: GameState) {
        let me = driver.localPlayer

        let count = min(previous.players.count, current.players.count)
        for i in 0..<count {
            if previous.players[i].alive && !current.players[i].alive {
                onDeath(player: current.players[i])
            }
            // Landing dust (either player).
            if !previous.players[i].onGround && current.players[i].onGround {
                let cx = current.players[i].pos.x.toFloat + config.playerWidth.toFloat / 2
                let cy = current.players[i].pos.y.toFloat + config.playerHeight.toFloat
                spawnDust(at: skPoint(cx, cy))
            }
        }

        // Quiver refill (walked-over reclaim or dash-catch): a small pop of dust
        // at the player plus a blip for the local player.
        for i in 0..<count where current.players[i].arrows > previous.players[i].arrows {
            let cx = current.players[i].pos.x.toFloat + config.playerWidth.toFloat / 2
            let cy = current.players[i].pos.y.toFloat + config.playerHeight.toFloat / 2
            spawnDust(at: skPoint(cx, cy))
            if i == me { AudioManager.shared.play("ui", on: self) }
        }

        if me < count {
            let before = previous.players[me]
            let after = current.players[me]
            if before.dashActiveTimer == 0 && after.dashActiveTimer > 0 {
                AudioManager.shared.play("dash", on: self)
            }
            if before.onGround && !after.onGround && after.vel.y.raw < 0 {
                AudioManager.shared.play("jump", on: self)
            }
        }

        let arrowCount = min(previous.arrows.count, current.arrows.count)
        for i in 0..<arrowCount {
            if !previous.arrows[i].active && current.arrows[i].active {
                let owner = Int(current.arrows[i].owner)
                if owner == me { AudioManager.shared.play("shoot", on: self) }
                if owner >= 0 && owner < playerNodes.count {
                    playerNodes[owner].playOneShot(.shoot)
                }
            }
        }
    }

    private static func animState(for p: PlayerState) -> AnimState {
        if !p.alive { return .die }
        if p.dashActiveTimer > 0 { return .dash }
        if !p.onGround { return p.vel.y.raw < 0 ? .jump : .fall }
        if abs(p.vel.x.raw) > runThreshold { return .run }
        return .idle
    }

    private func onDeath(player: PlayerState) {
        AudioManager.shared.play("hit", on: self)
        shakeScreen(intensity: 8)
        triggerFlash()
        // Quick zoom punch for impact (render-only; world is frozen in roundOver).
        world.run(.sequence([
            SKAction.scale(to: 1.07, duration: 0.05),
            SKAction.scale(to: 1.0, duration: 0.16),
        ]))
        let cx = player.pos.x.toFloat + config.playerWidth.toFloat / 2
        let cy = player.pos.y.toFloat + config.playerHeight.toFloat / 2
        spawnDeathParticles(at: skPoint(cx, cy))
    }

    private func spawnTrailPixel(at point: CGPoint, color: SKColor) {
        let p = SKSpriteNode(color: color, size: CGSize(width: 2, height: 2))
        p.position = point
        p.zPosition = 25
        world.addChild(p)
        p.run(.sequence([.fadeOut(withDuration: 0.28), .removeFromParent()]))
    }

    private func spawnDust(at point: CGPoint) {
        for _ in 0..<6 {
            let p = SKShapeNode(circleOfRadius: 1.5)
            p.fillColor = SKColor(white: 0.8, alpha: 0.7)
            p.strokeColor = .clear
            p.position = point
            p.zPosition = 40
            world.addChild(p)
            let dx = CGFloat.random(in: -10...10)
            let move = SKAction.moveBy(x: dx, y: CGFloat.random(in: 2...8), duration: 0.3)
            move.timingMode = .easeOut
            p.run(.sequence([.group([move, .fadeOut(withDuration: 0.3)]), .removeFromParent()]))
        }
    }

    private func shakeScreen(intensity: CGFloat) {
        var steps: [SKAction] = []
        for _ in 0..<6 {
            let dx = CGFloat.random(in: -intensity...intensity)
            let dy = CGFloat.random(in: -intensity...intensity)
            steps.append(.move(to: CGPoint(x: dx, y: dy), duration: 0.02))
        }
        steps.append(.move(to: .zero, duration: 0.02))
        world.run(.sequence(steps))
    }

    private func triggerFlash() {
        flash.removeAllActions()
        flash.alpha = 0.5
        flash.run(.fadeOut(withDuration: 0.18))
    }

    private func spawnDeathParticles(at point: CGPoint) {
        for _ in 0..<14 {
            let p = SKShapeNode(rectOf: CGSize(width: 3, height: 3))
            p.fillColor = SKColor(red: 1.0, green: 0.85, blue: 0.4, alpha: 1.0)
            p.strokeColor = .clear
            p.position = point
            p.zPosition = 50
            world.addChild(p)
            let angle = CGFloat.random(in: 0...(2 * .pi))
            let dist = CGFloat.random(in: 14...34)
            let move = SKAction.move(by: CGVector(dx: cos(angle) * dist, dy: sin(angle) * dist), duration: 0.4)
            move.timingMode = .easeOut
            let group = SKAction.group([move, .fadeOut(withDuration: 0.4)])
            p.run(.sequence([group, .removeFromParent()]))
        }
    }

    // MARK: - Render

    private func renderInterpolated(alpha: Float, dt: TimeInterval) {
        let (previous, current) = driver.renderStates()
        let halfW = config.playerWidth.toFloat / 2
        let halfH = config.playerHeight.toFloat / 2

        for i in 0..<playerNodes.count where i < current.players.count {
            let pPrev = previous.players[i]
            let pCur = current.players[i]
            let node = playerNodes[i]
            let cx = interp(pPrev.pos.x.toFloat + halfW, pCur.pos.x.toFloat + halfW, alpha, worldWidthPx)
            let cy = interp(pPrev.pos.y.toFloat + halfH, pCur.pos.y.toFloat + halfH, alpha, worldHeightPx)
            node.position = skPoint(cx, cy)
            // Facing flip + squash on ground / stretch with vertical speed.
            let facingSign: CGFloat = pCur.facing >= 0 ? 1 : -1
            let vy = abs(pCur.vel.y.toFloat)
            let yScale: CGFloat = pCur.onGround ? 0.92 : CGFloat(1.0 + min(0.28, vy * 0.022))
            node.yScale = yScale
            node.xScale = facingSign * (1.0 / yScale)
            node.setBaseState(Self.animState(for: pCur))
            node.update(CGFloat(dt))
        }

        for a in 0..<arrowNodes.count where a < current.arrows.count {
            let cur = current.arrows[a]
            let node = arrowNodes[a]
            if !cur.active {
                node.isHidden = true
                continue
            }
            node.isHidden = false
            let prev = previous.arrows[a]
            let cx: Float
            let cy: Float
            if prev.active {
                cx = interp(prev.pos.x.toFloat, cur.pos.x.toFloat, alpha, worldWidthPx)
                cy = interp(prev.pos.y.toFloat, cur.pos.y.toFloat, alpha, worldHeightPx)
            } else {
                cx = cur.pos.x.toFloat
                cy = cur.pos.y.toFloat
            }
            node.position = skPoint(cx, cy)
            node.zRotation = arrowRotation(cur)

            // Cosmetic trail: small fading pixel squares in the owner's
            // equipped trail color while the arrow is in flight.
            let owner = Int(cur.owner)
            if !cur.stuck && trailSpawnTick % 4 == 0 && owner >= 0 && owner < trailColors.count {
                spawnTrailPixel(at: node.position, color: trailColors[owner])
            }
        }
        trailSpawnTick &+= 1

        let me = driver.localPlayer
        if me < current.players.count {
            hud.text = "Arrows: \(current.players[me].arrows)/\(config.startingArrows)"
        }

        updateMatchLabels(current)
    }

    private func updateMatchLabels(_ state: GameState) {
        if state.scores.count >= 2 {
            scoreLabel.text = "\(state.scores[0])   -   \(state.scores[1])"
        }

        // Punch-scale the center label whenever its text changes.
        defer {
            let text = centerLabel.text ?? ""
            if text != lastCenterText {
                lastCenterText = text
                if !text.isEmpty {
                    centerLabel.removeAllActions()
                    centerLabel.setScale(1.7)
                    centerLabel.run(.scale(to: 1.0, duration: 0.25))
                }
            }
        }

        switch state.phase {
        case .countdown:
            // 60 sim ticks per second (audit fix: was /30, counting at 2x speed).
            let secondsLeft = Int((Double(state.phaseTimer) / 60.0).rounded(.up))
            centerLabel.text = secondsLeft > 0 ? "\(secondsLeft)" : "GO"
        case .playing:
            centerLabel.text = ""
        case .roundOver:
            centerLabel.text = "ROUND OVER"
        case .matchOver:
            let me = driver.localPlayer
            let localWon = state.winner == Int8(me)
            centerLabel.text = localWon ? "YOU WIN" : "YOU LOSE"
            if !matchEndFired {
                matchEndFired = true
                let kills = me < state.scores.count ? state.scores[me] : 0
                let rounds = state.scores.reduce(0, +)
                onMatchEnd?(localWon, kills, rounds)
            }
        }
    }

    private func skPoint(_ simX: Float, _ simY: Float) -> CGPoint {
        return CGPoint(x: CGFloat(simX), y: CGFloat(worldHeightPx - simY))
    }

    private func interp(_ from: Float, _ to: Float, _ t: Float, _ wrap: Float) -> Float {
        let delta = to - from
        if abs(delta) > wrap * 0.5 { return to }
        return from + delta * t
    }

    private func arrowRotation(_ arrow: ArrowState) -> CGFloat {
        if !arrow.stuck && (arrow.vel.x.raw != 0 || arrow.vel.y.raw != 0) {
            return CGFloat(atan2(Double(-arrow.vel.y.toFloat), Double(arrow.vel.x.toFloat)))
        }
        let angle = Float(arrow.dir) / 256.0 * 2.0 * .pi
        return CGFloat(-angle)
    }
}
