// MapTheme.swift
// Render-only world theming per map id. Each map belongs to one of five worlds
// (alien/castle/lava/sludge/aquatic - see Maps.themes); the world names the
// tileset folder and background image generated by tools/generate_pixel_art.py.
// The colors are fallbacks for when a texture is missing from the bundle.

import UIKit
import ArrowClashSim

struct MapTheme {
    let world: String
    let tile: UIColor
    let background: UIColor
}

enum MapThemes {
    // Fallback colors per world (match WORLDS in tools/generate_pixel_art.py).
    private static let worlds: [String: MapTheme] = [
        "alien":   MapTheme(world: "alien",   tile: rgb(96, 68, 138),   background: rgb(32, 26, 66)),
        "castle":  MapTheme(world: "castle",  tile: rgb(132, 130, 144), background: rgb(96, 60, 100)),
        "lava":    MapTheme(world: "lava",    tile: rgb(70, 58, 66),    background: rgb(56, 18, 22)),
        "sludge":  MapTheme(world: "sludge",  tile: rgb(112, 120, 112), background: rgb(44, 58, 44)),
        "aquatic": MapTheme(world: "aquatic", tile: rgb(198, 174, 126), background: rgb(20, 52, 100)),
    ]

    static func theme(for id: Int) -> MapTheme {
        let name = (id >= 0 && id < Maps.themes.count) ? Maps.themes[id] : "alien"
        return worlds[name] ?? worlds["alien"]!
    }

    private static func rgb(_ r: Int, _ g: Int, _ b: Int) -> UIColor {
        UIColor(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: 1)
    }
}
