// Maps.swift
// GENERATED by tools/generate_maps.py - do not edit by hand.
// 10 TowerFall-style arenas (20x12): grounded floors and side structures
// with occasional gaps for wrap. 'C' marks treasure chest spots.

public struct SpawnPoint: Equatable {
    public let x: Int
    public let y: Int
    public init(x: Int, y: Int) { self.x = x; self.y = y }
}

public struct MapDefinition: Equatable {
    public let id: Int
    public let name: String
    public let layout: [String]
    public let spawns: [SpawnPoint]
    public var cols: Int { layout.first?.count ?? 0 }
    public var rows: Int { layout.count }

    public func tileMap() -> TileMap {
        var solid = [Bool](repeating: false, count: cols * rows)
        for (r, line) in layout.enumerated() {
            for (c, ch) in line.enumerated() {
                solid[r * cols + c] = (ch == "#")
            }
        }
        return TileMap(cols: cols, rows: rows, solid: solid)
    }

    // Treasure chest spots: tile centers of 'C' cells in the layout.
    public var chests: [SpawnPoint] {
        var result: [SpawnPoint] = []
        for (r, line) in layout.enumerated() {
            for (c, ch) in line.enumerated() where ch == "C" {
                result.append(SpawnPoint(x: c * 16 + 8, y: r * 16 + 8))
            }
        }
        return result
    }
}

public enum Maps {
    public static let all: [MapDefinition] = [
        MapDefinition(id: 0, name: "Alien Meadow", layout: [  // theme: alien
            "....................",
            "....................",
            ".........C..........",
            "......########......",
            "....................",
            "..###.........###...",
            "....................",
            "..####.......####...",
            "....................",
            "....................",
            ".........CC.........",
            "####....####....####",
        ], spawns: [SpawnPoint(x: 19, y: 162), SpawnPoint(x: 275, y: 162)]),
        MapDefinition(id: 1, name: "Mothership", layout: [  // theme: alien
            "######........######",
            "....................",
            "........C...........",
            "......########......",
            "....................",
            "...##..........##...",
            "....................",
            "....................",
            "....................",
            "#####..........#####",
            "....................",
            "....................",
        ], spawns: [SpawnPoint(x: 35, y: 130), SpawnPoint(x: 275, y: 130)]),
        MapDefinition(id: 2, name: "Castle Walls", layout: [  // theme: castle
            "....................",
            "....................",
            "..##............##..",
            "..##.....C......##..",
            "..##...######...##..",
            "....................",
            "....................",
            "......##....##......",
            "....................",
            "....................",
            "....................",
            "########....########",
        ], spawns: [SpawnPoint(x: 19, y: 162), SpawnPoint(x: 291, y: 162)]),
        MapDefinition(id: 3, name: "Throne Room", layout: [  // theme: castle
            "####################",
            "....................",
            "....................",
            "...###........###...",
            "....................",
            ".........C..........",
            "........####........",
            "....................",
            "....................",
            "....................",
            "....................",
            "####################",
        ], spawns: [SpawnPoint(x: 35, y: 162), SpawnPoint(x: 275, y: 162)]),
        MapDefinition(id: 4, name: "Magma Core", layout: [  // theme: lava
            "#####..........#####",
            "....................",
            "....##........##....",
            "....................",
            ".........C..........",
            "........####........",
            "....................",
            "...####......####...",
            "....................",
            "....................",
            "....................",
            "######........######",
        ], spawns: [SpawnPoint(x: 19, y: 162), SpawnPoint(x: 291, y: 162)]),
        MapDefinition(id: 5, name: "Lava Falls", layout: [  // theme: lava
            "....................",
            "....................",
            "##......C.........##",
            "##....######......##",
            "....................",
            "....................",
            "....##........##....",
            "....................",
            "##................##",
            "....................",
            "....................",
            "####....####....####",
        ], spawns: [SpawnPoint(x: 51, y: 162), SpawnPoint(x: 259, y: 162)]),
        MapDefinition(id: 6, name: "Sludge Works", layout: [  // theme: sludge
            "....................",
            "....................",
            "....................",
            "..####........####..",
            "....................",
            ".........C..........",
            ".......######.......",
            "....................",
            "....##........##....",
            "....................",
            "....................",
            "#########..#########",
        ], spawns: [SpawnPoint(x: 19, y: 162), SpawnPoint(x: 291, y: 162)]),
        MapDefinition(id: 7, name: "Toxic Vats", layout: [  // theme: sludge
            "####################",
            "....................",
            "....................",
            "......C......C......",
            ".....###....###.....",
            "....................",
            "....................",
            "...##..........##...",
            "....................",
            "....................",
            ".........##.........",
            "#####...####...#####",
        ], spawns: [SpawnPoint(x: 35, y: 162), SpawnPoint(x: 275, y: 162)]),
        MapDefinition(id: 8, name: "Coral Reef", layout: [  // theme: aquatic
            "....................",
            "....................",
            "....##........##....",
            "....................",
            "........C...........",
            "......########......",
            "....................",
            "...##..........##...",
            "....................",
            "....................",
            "....................",
            "..################..",
        ], spawns: [SpawnPoint(x: 35, y: 162), SpawnPoint(x: 275, y: 162)]),
        MapDefinition(id: 9, name: "The Deep", layout: [  // theme: aquatic
            "##................##",
            "##................##",
            "....................",
            "....####..####......",
            "....................",
            ".........C..........",
            "......######........",
            "....................",
            "..##............##..",
            "....................",
            "....................",
            "####################",
        ], spawns: [SpawnPoint(x: 19, y: 162), SpawnPoint(x: 291, y: 162)]),
    ]

    public static var `default`: MapDefinition { all[0] }
    public static var count: Int { all.count }
    public static func byID(_ id: Int) -> MapDefinition {
        (id >= 0 && id < all.count) ? all[id] : all[0]
    }

    // World theme per map id (render-only; used by art/scene).
    public static let themes: [String] = [
        "alien", "alien", "castle", "castle", "lava", "lava", "sludge", "sludge", "aquatic", "aquatic",
    ]
}
